# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Testimonial
  description: Testimonial section
  icon: "3p"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: "We Felt Proud When People Love our"
  title_suffix: "Product"
  description: We believe that a good email marketing strategy is the key to growth. So we’re helping you grow your business with tools and resources that make email marketing easy.
  slider:
    - image: "/images/testimonial/logo-2.jpg"
      image_alt: Profile photo of the Head of Development
      author: "Sherlock Homes"
      designation: "Head of Dev. at Company"
      message: "Eget eu massa et consectetur. Mauris donec. Leo a, id sed duis proin sodales. Turpis viverra diam porttitor mattis morbi ac amet."
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
