# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Privacy Policy
  description: Privacy policy section
  icon: "lock"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  terms_and_conditions:
    - heading: Sendit Terms And Conditions
      description: "<p>By using Sendit, you agree to the terms and conditions listed on this page.</p><p>Sendit may change the terms on this page. We will take steps to notify you when this occurs, but you are responsible for staying up-to-date with these changes.</p>"
    - heading: Account Information & Payments
      description: "<ul><li>Fees must be paid at or before the date specified in your payment plan.</li><li>Failure to pay account fees may result in restricted or suspended access to your Sendit account.</li></ul>"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: html
