# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Team
  description: About Team section
  icon: "groups"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: Our leadership & Team Members
  team_members:
    - name: Cody Fisher
      designation: Co-Founder & CEO
      image: /images/team/team-member-1.jpg
      image_alt: "Team member: Cody Fisher"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
