# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Video
  description: About Video section
  icon: "play_circle"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: We Love our works
  description: On the other hand, we denounce with righteous indignation and
    dislike men who are so beguiled and demoralized by the charms of
    pleasure of the moment, so blinded by desire, that they cannot
    foresee the pain and trouble that are bound to ensue; and equal
    blame belongs to those who fail in their duty through weakness of
    will, which is the same as saying through shrinking from toil and
    pain. These cases are perfectly simple and easy to distinguish.
  button:
    link: https://www.linkedin.com/
    text: Follow on Linkedin
  video:
    image: /images/works/banner.jpg
    image_alt: Placeholder image for the video
    link: https://vimeo.com/45830194

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
