# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Hero
  description: About Hero section
  icon: "apps"
  tags: ["hero"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: One mission to make the better marketing
  description: We believe that a good email marketing strategy is the key to growth. So we’re helping you grow your business with tools and resources that make email marketing easy.
  hero_images:
    - image: /images/about/aboutfeature-two.png
      image_alt: People working
      placement: front_bottom
    - image: /images/about/aboutfeature-three.png
      image_alt: Group of people looking at a computer
      placement: back_top_right
    - image: /images/about/aboutfeature-four.png
      image_alt: Staff group photo
      placement: back_top_left
  button:
    text: "See more"
    link: "#counter-up"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
  placement:
    type: select
    options:
      values:
        - front_bottom
        - back_top_right
        - back_top_left
