# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Login
  description: Login section
  icon: "login"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: Log In
  fullname:
    heading: Full Name
    placeholder: Your Name
  email:
    heading: Email Address
    placeholder: Your Email
  checkbox_text: Remember Me
  log_in_button:
    text: "Log In"
  sign_up_button:
    link: "/signup"
    text: "Create an Account"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: 
  fullname:
    options:
      preview:
        icon: person
  email:
    options:
      preview:
        icon: email
  log_in_button:
    options:
      preview:
        icon: login
  sign_up_button:
    options:
      preview:
        icon: border_color
